export class ASN1Error extends Error { }
export class IllegalContent extends ASN1Error { }
export class IllegalEncoding extends IllegalContent { }
export class UnknownTagClass extends ASN1Error { }
export class UnknownEncoding extends ASN1Error { }
export class UnknownUniversalType extends ASN1Error { }
export class UnsupportedContentLength extends ASN1Error { }
export class UnsupportedUniversalType extends ASN1Error { }
export class UnsupportedTagClass extends ASN1Error { }
